const defaultState={goal:64000,contributors:[],ledger:[],items:[],expenses:[]};
const SUPABASE_URL='https://uueswblstandqnwtzndh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Ru81fqRUmkeaidxKjMSAFA_UzM7JKuQ';
const TRIP_ID='el-nido-demo';
let state=JSON.parse(localStorage.getItem('pixelState')||'null')||defaultState; const $=s=>document.querySelector(s); const money=n=>'₱'+Number(n).toLocaleString('en-PH');
let syncTimer;
function setSyncStatus(label,connected=false){const el=$('#syncStatus');if(el){el.textContent=`● ${label}`;el.style.color=connected?'#639b89':'#c48a5c'}}
function save(){localStorage.setItem('pixelState',JSON.stringify(state));clearTimeout(syncTimer);setSyncStatus('Saving…');syncTimer=setTimeout(syncToSupabase,400)}
async function supabaseRequest(path,options={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(await response.text());return response.status===204?null:response.json()}
async function syncToSupabase(){try{await supabaseRequest(`trips?id=eq.${TRIP_ID}`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:TRIP_ID,name:'El Nido escape',data:state,updated_at:new Date().toISOString()})});setSyncStatus('Synced just now',true)}catch(error){setSyncStatus('Local only');console.warn('Supabase sync unavailable:',error)}}
async function loadFromSupabase(){try{setSyncStatus('Connecting…');const rows=await supabaseRequest(`trips?id=eq.${TRIP_ID}&select=data`);if(rows?.[0]?.data&&Object.keys(rows[0].data).length){state=rows[0].data;localStorage.setItem('pixelState',JSON.stringify(state));render()}else await syncToSupabase();setSyncStatus('Synced',true)}catch(error){setSyncStatus('Local only');console.warn('Supabase load unavailable:',error)}}
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('')}
function avatar(c,initial){return `<div class="avatar avatar-${c||'teal'}">${initial}</div>`}
function renderCrew(){const html=state.contributors.length?state.contributors.map(p=>`<div class="crew-row">${avatar(p.color,p.initial)}<div class="crew-info"><b>${p.name}</b><small>${money(p.paid)} of ${money(p.pledge)} · ${p.paid>=p.pledge?'complete':'on track'}</small></div><div class="mini-progress"><span>${p.pledge?Math.round(p.paid/p.pledge*100):0}%</span><div class="progress-track"><div style="width:${p.pledge?Math.min(100,p.paid/p.pledge*100):0}%"></div></div></div></div>`).join(''):'<div class="empty-state">No members yet. Add your first tropa member to start tracking.</div>';$('#crewList').innerHTML=html;$('#fullCrew').innerHTML=html}
function renderLedger(){const rows=state.ledger.length?state.ledger.map(x=>`<div class="ledger-row"><span><b>${x.name}</b></span><span class="amount">+${money(x.amount)}</span><small>${x.date}</small><small>${x.note||'—'}</small></div>`).join(''):'<div class="empty-state">No contributions yet. Log the first payment to start the tracker.</div>';$('#ledger').innerHTML='<div class="ledger-row header"><span>PERSON</span><span>AMOUNT</span><span>DATE</span><span>NOTE</span></div>'+rows;$('#pendingBadge').textContent=state.contributors.filter(p=>p.paid<p.pledge).length}
function renderGoal(){const paid=state.contributors.reduce((a,p)=>a+p.paid,0), pct=Math.round(paid/state.goal*100), left=Math.max(0,state.goal-paid), perHead=Math.ceil(state.goal/Math.max(1,state.contributors.length));$('#goalAmount').textContent=money(state.goal);$('#goalSub').textContent=`${money(paid)} raised so far`;$('#goalPercent').textContent=pct+'%';$('#goalProgress').style.width=Math.min(100,pct)+'%';$('.goal-bottom').innerHTML=`<span>${money(left)} to go</span><span>Target · May 10, 2025</span>`;$('#insightText').innerHTML=`${money(left)} left to reach the group goal. Equal share for ${state.contributors.length} people is ${money(perHead)} each.`;$('#groupProgressStat').textContent=pct+'%';$('#groupProgressCopy').textContent=`${money(paid)} of ${money(state.goal)}`;$('#splitTargetStat').textContent=money(perHead);$('#remainingPerPersonStat').textContent=money(Math.ceil(left/Math.max(1,state.contributors.length)))}
function renderCountdown(){const trip=new Date('2027-05-18T00:00:00');const days=Math.max(0,Math.ceil((trip-new Date())/86400000));$('#countdown').innerHTML=`${days} <span>days</span>`}
function renderItinerary(){let total=0,cats={},members=Math.max(1,state.contributors.length);$('#dayList').innerHTML=state.items.length?state.items.map(d=>`<div class="day-card card"><div class="day-head"><div class="day-num"><b>${d.day}</b><small>${d.date}</small></div><div><b>${d.title}</b><span>${d.sub}</span></div><span class="muted">⌄</span></div>${d.items.map(i=>{let n=Number(i[2].replaceAll(',',''));total+=n;let cat=i[1].includes('Accommodation')?'Stay':i[1].includes('dinner')||i[1].includes('snacks')?'Food':i[1].includes('transfer')?'Transport':'Activities';cats[cat]=(cats[cat]||0)+n;return `<div class="item-row"><span>${i[0]}</span><div><b>${i[1]}${i[3]?'<span class="optional">OPTIONAL</span>':''}</b><small>Shared by ${members} people · ${money(Math.ceil(n/members))}/head</small></div><strong>${money(n)}</strong></div>`}).join('')}</div>`).join(''):'<div class="empty-state card">No gala added yet. Add your next trip, dinner, or activity above.</div>';$('#breakdownList').innerHTML=Object.entries(cats).map(([k,v])=>`<div class="break-item"><span>${k}</span><span>${money(v)}</span></div>`).join('')||'<div class="empty-state small">No costs yet.</div>';$('#itineraryTotal').textContent=money(total);$('#autoSplitTotal').textContent=money(Math.ceil(total/members));$('#previewItems').innerHTML=state.items.slice(0,2).map(d=>`<div class="itinerary-preview card"><div class="date-chip"><b>${d.day}</b><small>${d.date}</small></div><div><b>${d.title}</b><span>${d.sub}</span></div><strong>${money(d.items.reduce((s,i)=>s+Number(i[2].replaceAll(',','')),0))}</strong></div>`).join('')||'<div class="empty-state card">Your next gala will appear here.</div>'}
function renderSettle(){ $('#settleList').innerHTML=state.expenses.length?state.expenses.map(e=>`<div class="settle-row"><div class="avatars">${avatar('coral',initials(e[0])[0])}${avatar('gold',initials(e[1])[0])}</div><div><b>${e[0]}</b><span>pays</span><b>${e[1]}</b></div><strong>${e[2]}</strong></div>`).join(''):'<div class="empty-state">No shared expenses yet. Add one when someone advances for the group.</div>'}
function render(){renderCrew();renderLedger();renderGoal();renderItinerary();renderSettle();renderCountdown();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(type){$('#modal').classList.add('open');const contribution=type==='contribution',goal=type==='goal',item=type==='item',member=type==='member';$('#modalTitle').textContent=contribution?'Log a contribution':goal?'Set individual goal':item?'Add next gala':member?'Add member':'Add shared expense';$('#modalLabel').textContent=contribution||goal?'MONEY IN':item?'NEXT GALA':member?'THE CREW':'MONEY OUT';$('#entryPerson').innerHTML=state.contributors.map(p=>`<option>${p.name}</option>`).join('');$('#personField').style.display=item||member?'none':'grid';$('#descriptionField').style.display=contribution||goal?'none':'grid';$('#amountField').style.display=member?'none':'grid';$('#dateField').style.display=member?'none':'grid';$('#noteField').style.display=contribution||item?'grid':'none';$('#entryAmount').required=!member;$('#entryName').required=member;$('#entryAmount').value='';$('#entryName').value='';$('#entryNote').value='';$('#entryDate').value=new Date().toISOString().slice(0,10);$('#entryForm').dataset.type=type}
function switchTab(tab){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-view').forEach(v=>v.classList.toggle('active',v.id===tab+'View'));$('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#addContribution').onclick=()=>openModal('contribution');$('#setMemberGoal').onclick=()=>openModal('goal');$('#addItem').onclick=()=>openModal('item');$('#addExpense').onclick=()=>openModal('expense');$('#askHati').onclick=()=>toast(`Equal split: ${money(Math.ceil(Math.max(0,state.goal-state.contributors.reduce((a,p)=>a+p.paid,0))/Math.max(1,state.contributors.length)))} left per person.`);$('#insightBtn').onclick=()=>toast(`Group goal ÷ ${state.contributors.length} people = ${money(Math.ceil(state.goal/Math.max(1,state.contributors.length)))} each.`);$('#shareBtn').onclick=()=>{navigator.clipboard?.writeText(location.href);toast('Summary link copied — ready for the group chat!')};$('#markSettled').onclick=()=>{state.expenses=[];save();renderSettle();toast('All balances marked as settled 🎉')};$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#entryForm').onsubmit=e=>{e.preventDefault();let name=$('#entryPerson').value,amount=Number($('#entryAmount').value),date=new Date($('#entryDate').value).toLocaleDateString('en-US',{month:'short',day:'2-digit'}),type=e.target.dataset.type;if(type==='contribution'){let p=state.contributors.find(x=>x.name===name);p.paid+=amount;state.ledger.unshift({name,amount,date,note:$('#entryNote').value||'New contribution'})}else if(type==='goal'){let p=state.contributors.find(x=>x.name===name);p.pledge=amount}else if(type==='item'){const d=new Date($('#entryDate').value),label=$('#entryName').value.trim()||'New gala';state.items.push({day:String(d.getDate()),date:d.toLocaleDateString('en-US',{month:'short'}).toUpperCase(),title:label,sub:'Added by the group',items:[['✦',label,String(amount).replace(/\B(?=(\d{3})+(?!\d))/g,',')]]})}else{state.expenses.unshift([name,'Juan Dela Cruz',money(amount)])}save();render();$('#modal').classList.remove('open');e.target.reset();toast(type==='contribution'?'Contribution logged!':type==='goal'?'Individual goal updated!':type==='item'?'Next gala added!':'Shared expense added.')};$('#saveSettings').onclick=()=>{state.goal=Number($('#goalInput').value)||state.goal;save();render();toast('Trip settings saved.')};
$('#addMember').onclick=()=>openModal('member');
$('#entryForm').addEventListener('submit',e=>{if(e.target.dataset.type!=='member')return;e.preventDefault();e.stopImmediatePropagation();const name=$('#entryName').value.trim();if(!name)return;state.contributors.push({name,initial:name[0].toUpperCase(),pledge:Math.ceil(state.goal/Math.max(1,state.contributors.length+1)),paid:0,color:['teal','coral','gold','purple','blue'][state.contributors.length%5]});save();render();$('#modal').classList.remove('open');e.target.reset();toast('Member added!')},true);
render();
loadFromSupabase();
