const defaultState={goal:0,groupName:'',emoji:'',tripDate:'',contributors:[],ledger:[],items:[],expenses:[]};
const SUPABASE_URL='https://uueswblstandqnwtzndh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Ru81fqRUmkeaidxKjMSAFA_UzM7JKuQ';
const TRIP_ID='el-nido-demo';
let state=JSON.parse(localStorage.getItem('pixelState')||'null')||defaultState; const $=s=>document.querySelector(s); const money=n=>'₱'+Number(n).toLocaleString('en-PH');
let syncTimer;
function setSyncStatus(label,connected=false){const el=$('#syncStatus');if(el){el.textContent=`● ${label}`;el.style.color=connected?'#639b89':'#c48a5c'}}
function save(){localStorage.setItem('pixelState',JSON.stringify(state));clearTimeout(syncTimer);setSyncStatus('Saving…');syncTimer=setTimeout(syncToSupabase,400)}
async function supabaseRequest(path,options={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(await response.text());return response.status===204?null:response.json()}
async function syncToSupabase(){try{await supabaseRequest(`trips?id=eq.${TRIP_ID}`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:TRIP_ID,name:'El Nido escape',data:state,updated_at:new Date().toISOString()})});setSyncStatus('Synced just now',true)}catch(error){setSyncStatus('Local only');console.warn('Supabase sync unavailable:',error)}}
async function loadFromSupabase(){try{setSyncStatus('Connecting…');const rows=await supabaseRequest(`trips?id=eq.${TRIP_ID}&select=data`);if(rows?.[0]?.data&&Object.keys(rows[0].data).length){state=rows[0].data;localStorage.setItem('pixelState',JSON.stringify(state));render()}else await syncToSupabase();setSyncStatus('Synced',true)}catch(error){setSyncStatus('Local only');console.warn('Supabase load unavailable:',error)}}
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('')}
function avatar(c,initial){return `<div class="avatar avatar-${c||'teal'}">${initial}</div>`}
function renderIdentity(){const name=state.groupName||'Your next trip',emoji=state.emoji||'',people=state.contributors.length,date=state.tripDate?new Date(`${state.tripDate}T00:00:00`):null;$('#groupTitle').innerHTML=`${name} <span id="groupEmoji">${emoji}</span>`;$('#breadcrumbName').textContent=name;$('#groupSubtitle').textContent=people?`Set up the plan with your ${people} ${people===1?'member':'members'}.`:'Set up your group, goal, and first gala.';$('#crewLabel').textContent=`YOUR TROPA · ${people} ${people===1?'PERSON':'PEOPLE'}`;$('#sideTripName').textContent=name;$('#sideEmoji').textContent=emoji||'✦';$('#sideTripMeta').textContent=date?date.toLocaleDateString('en-US',{month:'long',year:'numeric'}):'Set up your gala';$('#countdownDate').textContent=date?`until ${date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}`:'Choose a trip date in settings';$('#groupNameInput').value=state.groupName||'';$('#emojiInput').value=state.emoji||'';$('#goalInput').value=state.goal||'';$('#dateInput').value=state.tripDate||''}
function renderCrew(){const html=state.contributors.length?state.contributors.map(p=>`<div class="crew-row">${avatar(p.color,p.initial)}<div class="crew-info"><b>${p.name}</b><small>${money(p.paid)} of ${money(p.pledge)} · ${p.paid>=p.pledge?'complete':'on track'}</small></div><div class="mini-progress"><span>${p.pledge?Math.round(p.paid/p.pledge*100):0}%</span><div class="progress-track"><div style="width:${p.pledge?Math.min(100,p.paid/p.pledge*100):0}%"></div></div></div></div>`).join(''):'<div class="empty-state">No members yet. Add your first tropa member to start tracking.</div>';$('#crewList').innerHTML=html;$('#fullCrew').innerHTML=html}
function renderLedger(){const rows=state.ledger.length?state.ledger.map(x=>`<div class="ledger-row"><span><b>${x.name}</b></span><span class="amount">+${money(x.amount)}</span><small>${x.date}</small><small>${x.note||'—'}</small></div>`).join(''):'<div class="empty-state">No contributions yet. Log the first payment to start the tracker.</div>';$('#ledger').innerHTML='<div class="ledger-row header"><span>PERSON</span><span>AMOUNT</span><span>DATE</span><span>NOTE</span></div>'+rows;$('#pendingBadge').textContent=state.contributors.filter(p=>p.paid<p.pledge).length}
function renderGoal(){const paid=state.contributors.reduce((a,p)=>a+p.paid,0),pct=state.goal?Math.round(paid/state.goal*100):0,left=Math.max(0,state.goal-paid),perHead=state.goal?Math.ceil(state.goal/Math.max(1,state.contributors.length)):0;$('#goalAmount').textContent=money(state.goal);$('#goalSub').textContent=`${money(paid)} raised so far`;$('#goalPercent').textContent=pct+'%';$('#goalProgress').style.width=Math.min(100,pct)+'%';$('.goal-bottom').innerHTML=`<span>${money(left)} to go</span><span>${state.goal?'Set your target in settings':'Add a group goal in settings'}</span>`;$('#insightText').innerHTML=state.goal?`${money(left)} left to reach the group goal. Equal share for ${state.contributors.length} people is ${money(perHead)} each.`:'Set a group goal to see the automatic split per person.';$('#groupProgressStat').textContent=pct+'%';$('#groupProgressCopy').textContent=`${money(paid)} of ${money(state.goal)}`;$('#splitTargetStat').textContent=money(perHead);$('#remainingPerPersonStat').textContent=money(state.goal?Math.ceil(left/Math.max(1,state.contributors.length)):0)}
function renderCountdown(){if(!state.tripDate){$('#countdown').innerHTML='— <span>days</span>';return}const trip=new Date(`${state.tripDate}T00:00:00`),days=Math.max(0,Math.ceil((trip-new Date())/86400000));$('#countdown').innerHTML=`${days} <span>days</span>`}
function renderItinerary(){let total=0,cats={},members=Math.max(1,state.contributors.length);$('#dayList').innerHTML=state.items.length?state.items.map(d=>`<div class="day-card card"><div class="day-head"><div class="day-num"><b>${d.day}</b><small>${d.date}</small></div><div><b>${d.title}</b><span>${d.sub}</span></div><span class="muted">⌄</span></div>${d.items.map(i=>{let n=Number(i[2].replaceAll(',',''));total+=n;let cat=i[1].includes('Accommodation')?'Stay':i[1].includes('dinner')||i[1].includes('snacks')?'Food':i[1].includes('transfer')?'Transport':'Activities';cats[cat]=(cats[cat]||0)+n;return `<div class="item-row"><span>${i[0]}</span><div><b>${i[1]}${i[3]?'<span class="optional">OPTIONAL</span>':''}</b><small>Shared by ${members} people · ${money(Math.ceil(n/members))}/head</small></div><strong>${money(n)}</strong></div>`}).join('')}</div>`).join(''):'<div class="empty-state card">No gala added yet. Add your next trip, dinner, or activity above.</div>';$('#breakdownList').innerHTML=Object.entries(cats).map(([k,v])=>`<div class="break-item"><span>${k}</span><span>${money(v)}</span></div>`).join('')||'<div class="empty-state small">No costs yet.</div>';$('#itineraryTotal').textContent=money(total);$('#autoSplitTotal').textContent=money(Math.ceil(total/members));$('#previewItems').innerHTML=state.items.slice(0,2).map(d=>`<div class="itinerary-preview card"><div class="date-chip"><b>${d.day}</b><small>${d.date}</small></div><div><b>${d.title}</b><span>${d.sub}</span></div><strong>${money(d.items.reduce((s,i)=>s+Number(i[2].replaceAll(',','')),0))}</strong></div>`).join('')||'<div class="empty-state card">Your next gala will appear here.</div>'}
function renderSettle(){const hasExpenses=state.expenses.length;$('#settleSummaryTitle').textContent=hasExpenses?`${state.expenses.length} shared expense${state.expenses.length===1?'':'s'} to settle`:'No shared expenses yet';$('#settleSummaryCopy').textContent=hasExpenses?'Review the transfers below before calling it even.':'Add an expense when someone pays upfront for the group.';$('#markSettled').style.display=hasExpenses?'inline-block':'none';$('#settleTransferHint').textContent=hasExpenses?'Review the transfers below':'Add expenses to calculate transfers';$('#settleList').innerHTML=hasExpenses?state.expenses.map(e=>`<div class="settle-row"><div class="avatars">${avatar('coral',initials(e[0])[0])}${avatar('gold',initials(e[1])[0])}</div><div><b>${e[0]}</b><span>pays</span><b>${e[1]}</b></div><strong>${e[2]}</strong></div>`).join(''):'<div class="empty-state">No shared expenses yet. Add one when someone advances for the group.</div>'}
function renderMilestones(){const thresholds=[{pct:25,label:'First steps',icon:'✓'},{pct:50,label:'Halfway there',icon:'✓'},{pct:75,label:'Almost golden',icon:'⌁'},{pct:100,label:'Beach unlocked',icon:'🏖'}];const paid=state.contributors.reduce((a,p)=>a+p.paid,0);const pct=state.goal?Math.round(paid/state.goal*100):0;const unlocked=thresholds.filter(t=>pct>=t.pct).length;$('#milestoneCount').textContent=`${unlocked} of ${thresholds.length} unlocked`;$('#milestoneList').innerHTML=thresholds.map(t=>{const done=pct>=t.pct;const current=!done&&(pct>=((thresholds[thresholds.indexOf(t)-1]||{pct:0}).pct));const cls=done?'done':current?'current':'';const icon=done?'✓':current?pct:t.icon;return `<div class="milestone ${cls}"><span class="milestone-icon">${icon}</span><b>${t.pct}%</b><small>${t.label}</small></div>`}).join('')}
function renderSummary(){const paid=state.contributors.reduce((s,p)=>s+p.paid,0),pct=state.goal?Math.round(paid/state.goal*100):0;$('#summaryTitle').textContent=state.groupName||'Your next trip';$('#summarySubtitle').textContent=state.tripDate?`Trip date · ${new Date(`${state.tripDate}T00:00:00`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}`:'Planado ang gala, klaro ang ambag.';$('#summaryGoal').textContent=money(state.goal);$('#summaryProgress').textContent=`${money(paid)} raised · ${pct}%`;$('#summaryItinerary').innerHTML=state.items.length?state.items.map(d=>`<div class="summary-line"><span>${d.day} ${d.date}</span><b>${d.title}</b><strong>${money(d.items.reduce((s,i)=>s+Number(i[2].replaceAll(',','')),0))}</strong></div>`).join(''):'<div class="summary-empty">Wala pang gala na nailalagay.</div>';$('#summaryMembers').innerHTML=state.contributors.length?state.contributors.map(p=>`<div class="summary-line"><span class="summary-avatar">${p.initial}</span><b>${p.name}</b><strong>${money(p.paid)} / ${money(p.pledge)}</strong></div>`).join(''):'<div class="summary-empty">Wala pang members o ambag.</div>'}
function render(){renderIdentity();renderCrew();renderLedger();renderGoal();renderItinerary();renderSettle();renderCountdown();renderMilestones();renderSummary();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(type){$('#modal').classList.add('open');const contribution=type==='contribution',goal=type==='goal',item=type==='item',member=type==='member';$('#modalTitle').textContent=contribution?'Log a contribution':goal?'Set individual goal':item?'Add next gala':member?'Add member':'Add shared expense';$('#modalLabel').textContent=contribution||goal?'MONEY IN':item?'NEXT GALA':member?'THE CREW':'MONEY OUT';$('#entryPerson').innerHTML=state.contributors.map(p=>`<option>${p.name}</option>`).join('');$('#personField').style.display=item||member?'none':'grid';$('#descriptionField').style.display=contribution||goal?'none':'grid';$('#amountField').style.display=member?'none':'grid';$('#dateField').style.display=member?'none':'grid';$('#noteField').style.display=contribution||item?'grid':'none';$('#entryAmount').required=!member;$('#entryName').required=member;$('#entryAmount').value='';$('#entryName').value='';$('#entryNote').value='';$('#entryDate').value=new Date().toISOString().slice(0,10);$('#entryForm').dataset.type=type}
function switchTab(tab){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-view').forEach(v=>v.classList.toggle('active',v.id===tab+'View'));$('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#addContribution').onclick=()=>openModal('contribution');$('#setMemberGoal').onclick=()=>openModal('goal');$('#addItem').onclick=()=>openModal('item');$('#addExpense').onclick=()=>openModal('expense');$('#askHati').onclick=()=>toast(`Equal split: ${money(Math.ceil(Math.max(0,state.goal-state.contributors.reduce((a,p)=>a+p.paid,0))/Math.max(1,state.contributors.length)))} left per person.`);$('#insightBtn').onclick=()=>toast(`Group goal ÷ ${state.contributors.length} people = ${money(Math.ceil(state.goal/Math.max(1,state.contributors.length)))} each.`);$('#shareBtn').onclick=()=>{navigator.clipboard?.writeText(location.href);toast('Summary link copied — ready for the group chat!')};$('#markSettled').onclick=()=>{state.expenses=[];save();renderSettle();toast('All balances marked as settled 🎉')};$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#entryForm').onsubmit=e=>{e.preventDefault();let name=$('#entryPerson').value,amount=Number($('#entryAmount').value),date=new Date($('#entryDate').value).toLocaleDateString('en-US',{month:'short',day:'2-digit'}),type=e.target.dataset.type;if(type==='contribution'){let p=state.contributors.find(x=>x.name===name);p.paid+=amount;state.ledger.unshift({name,amount,date,note:$('#entryNote').value||'New contribution'})}else if(type==='goal'){let p=state.contributors.find(x=>x.name===name);p.pledge=amount}else if(type==='item'){const d=new Date($('#entryDate').value),label=$('#entryName').value.trim()||'New gala';state.items.push({day:String(d.getDate()),date:d.toLocaleDateString('en-US',{month:'short'}).toUpperCase(),title:label,sub:'Added by the group',items:[['✦',label,String(amount).replace(/\B(?=(\d{3})+(?!\d))/g,',')]]})}else{state.expenses.unshift([name,'Juan Dela Cruz',money(amount)])}save();render();$('#modal').classList.remove('open');e.target.reset();toast(type==='contribution'?'Contribution logged!':type==='goal'?'Individual goal updated!':type==='item'?'Next gala added!':'Shared expense added.')};$('#saveSettings').onclick=()=>{state.goal=Number($('#goalInput').value)||state.goal;save();render();toast('Trip settings saved.')};
$('#addMember').onclick=()=>openModal('member');
$('#entryForm').addEventListener('submit',e=>{if(e.target.dataset.type!=='member')return;e.preventDefault();e.stopImmediatePropagation();const name=$('#entryName').value.trim();if(!name)return;state.contributors.push({name,initial:name[0].toUpperCase(),pledge:Math.ceil(state.goal/Math.max(1,state.contributors.length+1)),paid:0,color:['teal','coral','gold','purple','blue'][state.contributors.length%5]});save();render();$('#modal').classList.remove('open');e.target.reset();toast('Member added!')},true);
render();
$('#saveSettings').onclick=()=>{state.groupName=$('#groupNameInput').value.trim();state.emoji=$('#emojiInput').value.trim();state.goal=Number($('#goalInput').value)||0;state.tripDate=$('#dateInput').value;save();render();toast('Trip settings saved!')};
$('#shareBtn').onclick=()=>{$('#shareModal').classList.add('open');renderSummary()};$('#summaryClose').onclick=()=>$('#shareModal').classList.remove('open');$('#shareModal').onclick=e=>{if(e.target.id==='shareModal')$('#shareModal').classList.remove('open')};$('#copySummary').onclick=()=>{const text=`${state.groupName||'Your next trip'} · ${money(state.goal)} goal · ${money(state.contributors.reduce((s,p)=>s+p.paid,0))} raised`;navigator.clipboard?.writeText(text);toast('Summary copied!')};
loadFromSupabase();
